security:
    enable_authenticator_manager: true
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        database_users:
            entity:
                class: App\Entity\User
                property: identifier
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true

            entry_point: App\Security\LoginFormAuthenticator

            custom_authenticators:
                - App\Security\LoginFormAuthenticator
                - App\Security\GoogleAuthenticator
                - App\Security\GitHubAuthenticator

            form_login:
                login_path: login
                check_path: login

            logout:
                path: /logout
                target: /

            remember_me:
                secret: '%kernel.secret%'
                path: /
                always_remember_me: true
                name: S3C0DERREMEMBERME

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
