build:
    dependencies:
        override:
            - npm install -g 'yarn'
            - yarn install
            - yarn dev
            - composer install
            - cp .env.scrutinizer .env
    nodes:
        my-node:
            services:
                # For available tags, see https://hub.docker.com/_/postgres/
                postgres: 10

coding_style:
    php:
        spaces:
            within:
                brackets: false
