build:
    nodes:
        my-node:
            services:
                # For available tags, see https://hub.docker.com/_/postgres/
                postgres: 10
    dependencies:
        override:
            - npm install -g 'yarn'
            - yarn install
            - yarn dev
            - composer install
            - cp .env.scrutinizer .env
    project_setup:
        - bin/console doctrine:migrations:migrate -n
        - bin/console doctrine:fixtures:load -n

coding_style:
    php:
        spaces:
            within:
                brackets: false
