build:
    dependencies:
        override:
            - npm install -g 'yarn'
            - yarn install
            - yarn dev
            - composer install

coding_style:
    php:
        spaces:
            within:
                brackets: false
