language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit
env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"
php:
  - 8.0
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

services:
  - postgresql

before_script:
#  - psql -c 'create database travis_ci_test;' -U postgres
  - cp .env.travis .env
  - composer install
  - nvm install 12
  - yarn install
  - yarn dev
  - bin/console doctrine:database:create -n
  - bin/console doctrine:migrations:migrate -n
  - bin/console doctrine:fixtures:load -n

script:
  - SYMFONY_DEPRECATIONS_HELPER=disabled ./bin/phpunit $PHPUNIT_FLAGS
#  - make tests
#  - cat ./var/log/test.log

#after_script:
#  - ./bin/console TravisFinishedNofitication
